### ISSUE TITLE
The tide correction figure isn't up to date

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/Coastseg_manuscript#5]
The tide correction figure present in the pdf is not the figure that was updated. It should be `figs/coastseg_figure_2.png`, but its still the old version of the figure. I'm not sure if this is a rendering issue but I thought I'd bring it up
![image](https://github.com/Doodleverse/Coastseg_manuscript/assets/61564689/11e0e10c-2b05-41fd-a1c3-561504fb791e)

**Comment by ddbuscombe** [comment]
Oh, that's just because I didnt compile the pdf locally before pushing to GH. The formatted version is ok. I will remember next time to convert then push
